language: ruby

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose --env-file .env.dev.s3 build

before_script:
  - docker-compose run --rm --no-deps web echo 'Gems now pre-installed.'
  - docker-compose --env-file .env.dev.s3 up -d
  - docker ps
  - docker-compose run --no-deps web bundle exec rake db:migrate
  - docker-compose run --no-deps web bundle exec rake db:create RAILS_ENV=test
  - docker-compose run --no-deps web bundle exec rake db:migrate RAILS_ENV=test

script:
  - docker-compose run --no-deps web bundle exec rspec --format documentation

after_script:
  - docker-compose down