version: '3'
services:
  db:
    image: postgres:10.10
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker_postgres_rails
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=cw_ovp_development
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./tmp/redis:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_USERNAME=docker_postgres_rails
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=cw_ovp_development
      - DATABASE_URL=db
      - DATABASE_PORT=5432
      - REDIS_SERVER_URL=redis://redis:6379/0
      - REDIS_CLIENT_URL=redis://redis:6379/0
    volumes:
      - .:/myapp
      - ~/storage:/storage
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
  sidekiq:
    build: .
    restart: always
    command: bundle exec sidekiq
    environment:
      - REDIS_SERVER_URL=redis://redis:6379/0
      - REDIS_CLIENT_URL=redis://redis:6379/0
    volumes:
      - .:/myapp
      - ~/storage:/storage
    depends_on:
      - 'redis'