development:
  adapter: redis
  url: <%= ENV['CABLE_REDIS_SERVER_URL'] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['CABLE_REDIS_SERVER_URL'] %>
  channel_prefix: CW_Encoding_production
